USE [master]
GO

/****** Object:  Database [QLNS]    Script Date: 6/14/2022 9:33:18 PM ******/
CREATE DATABASE [QLNS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLNS_Data', FILENAME = N'D:\CSDL\QLNS_Data.MDF' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'QLNS_Log', FILENAME = N'D:\CSDL\QLNS_Log.LDF' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLNS].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [QLNS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLNS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLNS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLNS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLNS] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLNS] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [QLNS] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [QLNS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLNS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLNS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLNS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLNS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLNS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLNS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLNS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QLNS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLNS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLNS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLNS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLNS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLNS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLNS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLNS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [QLNS] SET  MULTI_USER 
GO

ALTER DATABASE [QLNS] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [QLNS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QLNS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QLNS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [QLNS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QLNS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QLNS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QLNS] SET  READ_WRITE 
GO

